### ISSUE TITLE
Sorting doesn't work for subpages

### ISSUE THREAD

**Issue by dhensby** [micschk/silverstripe-gridfieldpages#1]
At the moment Subpages is `$pages = $this->AllChildrenIncludingDeleted();` and this returns an `ArrayList` of `SiteTree` objects.

For a variety of reasons, an `ArrayList` is not compatible with gridfieldextensions/sortablerows.

**Comment by micschk** [comment]
Sorry - only partially implemented this, just pushed some changes. If you'd like to confirm sorting now works as expected I'll close the issue.
